apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
        # http:
        #   path: "/v1/traces"
        #   timeout: 5s
        #   headers:
        #     - name: "custom-header"
        #       value: "custom value"
        resource_detectors:
          environment: {}